apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cloud-native-postgresql
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: cloud-native-postgresql
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: cloud-native-postgresql.v1.7.1