apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: cp4a-dev-env
  namespace: openshift-gitops
spec:
  destination:
    namespace: cp4a
    server: https://kubernetes.default.svc
  project: cp4a
  source:
    path: environments/cp4a-dev/env/overlays
    repoURL: https://github.com/ibm-cloud-architecture/dba-gitops-catalog.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

