apiVersion: processmining.ibm.com/v1beta1
kind: ProcessMining
metadata:
  name: processmining
spec:
  version : 1.11.1
  license:
    accept: true
    cloudPak: IBM Cloud Pak for Business Automation
  defaultStorageClassName: ibmc-file-gold-gid