apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cloud-native-postgresql
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: cloud-native-postgresql
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: cloud-native-postgresql.v1.9.2